# @prompt address
// http://localhost:3001
// https://phonebook-alexmerino.fly.dev
POST {{address}}/api/persons
Content-Type: application/json

{
    "name": "Martin Heidegger",
    "number": "55 6677 8899"
}

###
# @prompt address
POST {{address}}/api/persons
Content-Type: application/json

{
    "name": "Plato",
    "number": null
}

###
// Existing entry
# @prompt address
POST {{address}}/api/persons
Content-Type: application/json

{
    "name": "Ada Lovelace",
    "number": "55 6677 8899"
}